//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekres.Screenshot_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nekres.Screenshot_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A duplicate image name was specified! ähnelt.
        /// </summary>
        internal static string A_duplicate_image_name_was_specified_ {
            get {
                return ResourceManager.GetString("A duplicate image name was specified!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        internal static string Are_you_sure_ {
            get {
                return ResourceManager.GetString("Are you sure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By default, screenshots are sent to the Recycle Bin so that they can be recovered if needed.
        ///When this feature is disabled, deleted screenshots are removed from the hard disk and their space is marked as overwriteable. ähnelt.
        /// </summary>
        internal static string By_default__screenshots_are_sent_to_the_Recycle_Bin_so_that_they_can_be_recovered_if_needed__nWhen_this_feature_is_disabled__deleted_screenshots_are_removed_from_the_hard_disk_and_their_space_is_marked_as_overwriteable_ {
            get {
                return ResourceManager.GetString("By default, screenshots are sent to the Recycle Bin so that they can be recovered" +
                        " if needed.\\nWhen this feature is disabled, deleted screenshots are removed from" +
                        " the hard disk and their space is marked as overwriteable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose your preferred image format. ähnelt.
        /// </summary>
        internal static string Choose_your_preferred_image_format_ {
            get {
                return ResourceManager.GetString("Choose your preferred image format.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click To Zoom ähnelt.
        /// </summary>
        internal static string Click_To_Zoom {
            get {
                return ResourceManager.GetString("Click To Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Image? ähnelt.
        /// </summary>
        internal static string Delete_Image_ {
            get {
                return ResourceManager.GetString("Delete Image?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete sends to Recycle Bin ähnelt.
        /// </summary>
        internal static string Delete_sends_to_Recycle_Bin {
            get {
                return ResourceManager.GetString("Delete sends to Recycle Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Screenshot Notification ähnelt.
        /// </summary>
        internal static string Disable_Screenshot_Notification {
            get {
                return ResourceManager.GetString("Disable Screenshot Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disables the icon in the navigation menu. ähnelt.
        /// </summary>
        internal static string Disables_the_corner_icon_in_the_navigation_menu_ {
            get {
                return ResourceManager.GetString("Disables the corner icon in the navigation menu.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disables the notification when a new screenshot has been captured. ähnelt.
        /// </summary>
        internal static string Disables_the_notification_when_a_new_screenshot_has_been_captured_ {
            get {
                return ResourceManager.GetString("Disables the notification when a new screenshot has been captured.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to delete image {0}. ähnelt.
        /// </summary>
        internal static string Failed_to_delete_image__0__ {
            get {
                return ResourceManager.GetString("Failed to delete image {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favourite ähnelt.
        /// </summary>
        internal static string Favourite {
            get {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Options ähnelt.
        /// </summary>
        internal static string General_Options {
            get {
                return ResourceManager.GetString("General Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Corner Icon ähnelt.
        /// </summary>
        internal static string Hide_Corner_Icon {
            get {
                return ResourceManager.GetString("Hide Corner Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Format ähnelt.
        /// </summary>
        internal static string Image_Format {
            get {
                return ResourceManager.GetString("Image Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image name cannot be empty. ähnelt.
        /// </summary>
        internal static string Image_name_cannot_be_empty_ {
            get {
                return ResourceManager.GetString("Image name cannot be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mute Screenshot Sound ähnelt.
        /// </summary>
        internal static string Mute_Screenshot_Sound {
            get {
                return ResourceManager.GetString("Mute Screenshot Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mutes the sound alert when a new screenshot has been captured. ähnelt.
        /// </summary>
        internal static string Mutes_the_sound_alert_when_a_new_screenshot_has_been_captured_ {
            get {
                return ResourceManager.GetString("Mutes the sound alert when a new screenshot has been captured.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a different image name. ähnelt.
        /// </summary>
        internal static string Please_enter_a_different_image_name_ {
            get {
                return ResourceManager.GetString("Please enter a different image name.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename Image ähnelt.
        /// </summary>
        internal static string Rename_Image {
            get {
                return ResourceManager.GetString("Rename Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screenshot ähnelt.
        /// </summary>
        internal static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screenshot Created! ähnelt.
        /// </summary>
        internal static string Screenshot_Created_ {
            get {
                return ResourceManager.GetString("Screenshot Created!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screenshot Options ähnelt.
        /// </summary>
        internal static string Screenshot_Options {
            get {
                return ResourceManager.GetString("Screenshot Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search... ähnelt.
        /// </summary>
        internal static string Search___ {
            get {
                return ResourceManager.GetString("Search...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sound Options ähnelt.
        /// </summary>
        internal static string Sound_Options {
            get {
                return ResourceManager.GetString("Sound Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stereoscopic ähnelt.
        /// </summary>
        internal static string Stereoscopic {
            get {
                return ResourceManager.GetString("Stereoscopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Take a normal screenshot. ähnelt.
        /// </summary>
        internal static string Take_a_normal_screenshot_ {
            get {
                return ResourceManager.GetString("Take a normal screenshot.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Take a stereoscopic screenshot. ähnelt.
        /// </summary>
        internal static string Take_a_stereoscopic_screenshot_ {
            get {
                return ResourceManager.GetString("Take a stereoscopic screenshot.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following characters are not allowed: {0} ähnelt.
        /// </summary>
        internal static string The_following_characters_are_not_allowed___0_ {
            get {
                return ResourceManager.GetString("The following characters are not allowed: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The image doesn&apos;t exist anymore! ähnelt.
        /// </summary>
        internal static string The_image_file_doesn_t_exist_anymore_ {
            get {
                return ResourceManager.GetString("The image file doesn\'t exist anymore!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The image is in use by another process. ähnelt.
        /// </summary>
        internal static string The_image_file_is_in_use_by_another_process_ {
            get {
                return ResourceManager.GetString("The image file is in use by another process.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The image name contains invalid characters. ähnelt.
        /// </summary>
        internal static string The_image_name_contains_invalid_characters_ {
            get {
                return ResourceManager.GetString("The image name contains invalid characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to rename image {0}. ähnelt.
        /// </summary>
        internal static string Unable_to_rename_image__0__ {
            get {
                return ResourceManager.GetString("Unable to rename image {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfavourite ähnelt.
        /// </summary>
        internal static string Unfavourite {
            get {
                return ResourceManager.GetString("Unfavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to permanently destroy {0}. ähnelt.
        /// </summary>
        internal static string You_are_about_to_permanently_destroy__0__ {
            get {
                return ResourceManager.GetString("You are about to permanently destroy {0}.", resourceCulture);
            }
        }
    }
}
